### ISSUE TITLE
When this will get ported to Firefox?

### ISSUE THREAD

**Issue by goliv04053** [isaackogan/Chromegle#2]
I'm a Firefox user, and this could be interesting on Firefox Add-ons.

**Comment by isaackogan** [comment]
Eek, I'd like to port it but I know nothing about their marketplace, nor do I know if this goes against their TOS (it might). I'll look into it.

**Comment by isaackogan** [comment]
Looking into.

**Comment by isaackogan** [comment]
Not possible: Firefox does not support manifest v3 yet. When it does, I will look into this. It is _possible_ that I can just port it over without a separate version due to Firefox's fantastic Chromium support. Please [see here](https://discourse.mozilla.org/t/manifest-version-3-is-not-supported-for-firefox-extensions/80651) for reference.
